name: 'Add Eclipse Che links to try online'
description: 'Handle all triage fo this repository'
inputs:
  github-token:
    description: 'GITHUB token used to add PR check'
    required: true
  add-comment:
    description: If 'true', it will add comments on each PR with a link to try PR with Eclipse Che
    required: false
    default: false
  add-status:
    description: If 'true', it will add a PR status check on each PR with a link to try PR with Eclipse Che
    required: false
    default: true
runs:
  using: 'docker'
  image: './action.Dockerfile'
